# Generated by Django 4.2.6 on 2023-10-24 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "company_name",
                    models.CharField(
                        help_text="Enter Company Name",
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "Description",
                    models.TextField(
                        help_text="Enter About the Company", max_length=200, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="position",
            fields=[
                (
                    "position_name",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="skills",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skill_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="vacant_position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role_description",
                    models.TextField(
                        help_text="Enter description about Role..",
                        max_length=400,
                        null=True,
                    ),
                ),
                ("exp", models.IntegerField(default=0)),
                (
                    "company_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="info.company"
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        help_text="Select position for the company",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="info.position",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="position",
            name="reqd_skill",
            field=models.ManyToManyField(to="info.skills"),
        ),
    ]
