# Generated by Django 4.2.6 on 2023-10-26 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0006_remove_user_details_name_user_details_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user_details",
            name="description",
            field=models.TextField(help_text="Enter about you", null=True),
        ),
    ]
