# Generated by Django 4.2.6 on 2023-10-26 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0007_user_details_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user_details",
            old_name="phone",
            new_name="phone_no",
        ),
    ]
