# Generated by Django 4.2.6 on 2023-10-26 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0008_rename_phone_user_details_phone_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_details",
            name="age",
            field=models.IntegerField(help_text="Enter your age", null=True),
        ),
        migrations.AlterField(
            model_name="user_details",
            name="known_skills",
            field=models.ManyToManyField(
                help_text="Choose your skiils", null=True, to="info.skills"
            ),
        ),
    ]
