# Generated by Django 4.2.6 on 2023-10-26 19:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0010_alter_user_details_known_skills"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vacant_position",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
    ]
