# Generated by Django 4.2.6 on 2023-10-26 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0011_alter_vacant_position_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="vacant_position",
            name="company_description",
            field=models.TextField(
                help_text="Enter Description about Company", max_length=400, null=True
            ),
        ),
        migrations.AlterField(
            model_name="vacant_position",
            name="company_name",
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name="Company",
        ),
    ]
