# Generated by Django 4.2.6 on 2023-10-26 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0012_vacant_position_company_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vacant_position",
            name="username",
            field=models.CharField(default="", max_length=100),
        ),
    ]
