# Generated by Django 4.2.6 on 2023-10-27 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0013_vacant_position_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user_details",
            name="application",
            field=models.ManyToManyField(
                help_text="Applied Companies", null=True, to="info.vacant_position"
            ),
        ),
    ]
