# Generated by Django 4.2.6 on 2023-10-27 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0014_user_details_application"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vacant_position",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
