# Generated by Django 4.2.6 on 2023-10-27 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0015_alter_vacant_position_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vacant_position",
            name="username",
        ),
    ]
