# Generated by Django 4.2.6 on 2023-11-02 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0017_vacant_position_workplace_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_details",
            name="application",
            field=models.ManyToManyField(
                help_text="Applied Companies", to="info.vacant_position"
            ),
        ),
    ]
