# Generated by Django 4.2.6 on 2023-11-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0018_alter_user_details_application"),
    ]

    operations = [
        migrations.AddField(
            model_name="vacant_position",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
