# Generated by Django 4.2.6 on 2023-11-05 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0019_vacant_position_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vacant_position",
            name="id",
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
