# Generated by Django 4.2.6 on 2023-11-05 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0022_alter_vacant_position_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vacant_position",
            old_name="id",
            new_name="username",
        ),
    ]
